### PR TITLE
Fixes $SAFE issue on Ruby 2.3+ and modernizes Travis builds

### LINKED ISSUE #278: $SAFE setting incompatable with Ruby 2.3.0
https://github.com/technicalpickles/jeweler/blob/master/lib/jeweler/gemspec_helper.rb#L51

$SAFE values 2 thru 4 are now obsolete with Ruby 2.3.0. As a result I get this when I attempt to do "rake gemspec --trace":

    $ rake gemspec --trace
    ** Invoke gemspec (first_time)
    ** Invoke gemspec:generate (first_time)
    ** Invoke version_required (first_time)
    ** Execute version_required
    ** Execute gemspec:generate 
    Generated: rubyneat.gemspec
    ** Invoke gemspec:validate (first_time)
    ** Invoke gemspec_required (first_time)
    ** Execute gemspec_required
    ** Execute gemspec:validate
    rubyneat.gemspec is invalid. See the backtrace for more details.
    rake aborted!
    ArgumentError: $SAFE=2 to 4 are obsolete
    rubyneat.gemspec:1:in `block in parse'
    /home/alveric/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/jeweler-  2.0.1/lib/jeweler/gemspec_helper.rb:51:in `eval'
    /home/alveric/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/jeweler-2.0.1/lib/jeweler/gemspec_helper.rb:51:in `block in parse'
    Tasks: TOP => gemspec => gemspec:validate

### PR DESCRIPTION
**Pull request by steakknife**
Fixes #278, #279 

Credit to @mihael

### CODE REVIEW

**Comment by technicalpickles** [comment]
Thanks for doing this! Do you have any interesting in helping contribute to jeweler in general? If you do, I'd be happy to add you as a collaborator and give you access to the gem.

Otherwise, I can merge and release this later.

**Comment by steakknife** [comment]
Welcome back to the living! Jeweler hasn't seen a release since 2014, so "later" without a specific deadline doesn't sound like a genuine commitment.  I'm super crushed at work and a side-project right now, and just did this to fix a friend's build. :( I'll lump in a couple of the other useful commits in, but maybe someone else in one of the open PR's might be interested?

**Comment by steakknife** [comment]
The best I can do right now.

**Comment by technicalpickles** [comment]
@steakknife thank you for taking time to put together this work, and at least considering the possibility of contributing more. You must be a good friend to dive into fix jeweler to fix their build :grinning: I can appreciate being crushed with work and other life things, as that's what happened to and resulted in being an absentee gem maintainer

I could merge this now, but I don't think that will solve the underlying problem of me not mindfully maintaining this project. I filed https://github.com/technicalpickles/jeweler/issues/283 to figure that out. In the short term, people could consider either using @steakknife's fork, or  https://github.com/flajann2/juwelier (I am not sure if it's API compatible yet).

**Comment by flajann2** [comment]
I released a new gem with the $SAFE fix in place, but the Travis modernization looks interesting.

**Comment by flajann2** [comment]
Can you pull and merge with the latest and resolve the conflicts? Then I'll merge your pull request. Thanks.

**Comment by flajann2** [comment]
Resolved the conflicts.

**Comment by flajann2** [comment]
All looks good with the merge.

**Pull request closed without merging**
